spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: MyChat-UserMicroservice
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:9092
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?currentSchema=${DATABASE_CURRENT_SCHEMA}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:liquibase/db.changelog.yaml
    default-schema: ${DATABASE_CURRENT_SCHEMA}

server:
  port: ${MAIN_PORT}

jwt:
  secretKey: dXNlLXN0cm9uZy1hbmQtdmFsaWQtYmFzZTY0LWtleQ==
  accessLiveTime: 86400
  refreshLiveTime: 8640000

minio:
  bucket: images
  url: ${MINIO_URL:http://localhost:9000}
  accessKey: miniominio
  secretKey: miniominio
